/*
 Copyright 2010 Google Inc.  All Rights Reserved.
 Your use of this software is subject to the Terms of Service located
 at https://chrome.google.com/extensions/intl/en/gallery_tos.html.
*/
var h;var k=function(a,b,c){return a.call.apply(a.bind,arguments)},n=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},p=function(a,b,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?k:n;return p.apply(null,arguments)};var q=/https?:\/\/(?:.+\.)?google\.[a-z]{2,3}(?:\.[a-z]{2})?(?:\:[0-9]+)?\/(?:advanced_)?search.*(([?&]q=)([^&]+))/,r=/https?:\/\/(?:.+\.)?google\.[a-z]{2,3}(?:\.[a-z]{2})?(?:\:[0-9]+)?\/(?:webhp[^#]*)?(#((?:.+&)?q=)([^&]+)(.*)&fp=[^&]+)/,t=/&/g,u=/</g,v=/>/g,w=/\"/g;function x(a){return a?a.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;").replace(w,"&quot;"):""}function y(a){return q.test(a)||r.test(a)}function z(a){return y(a)&&/[?&#](qscrl|espv)=/.test(a)}
function A(a,b,c,d,e,f,l,m){return p.apply(null,arguments)};var B="StopIteration"in this?this.StopIteration:{message:"StopIteration",stack:""},C=function(){};C.prototype.next=function(){throw B;};C.prototype.__iterator__=function(){return this};var D=function(a,b){this.map_={};this.keys_=[];this.version_=this.count_=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};D.prototype.getCount=function(){return this.count_};D.prototype.getValues=function(){E(this);for(var a=[],b=0;b<this.keys_.length;b++)a.push(this.map_[this.keys_[b]]);return a};D.prototype.getKeys=function(){E(this);return this.keys_.concat()};
D.prototype.remove=function(a){return Object.prototype.hasOwnProperty.call(this.map_,a)?(delete this.map_[a],this.count_--,this.version_++,this.keys_.length>2*this.count_&&E(this),!0):!1};
var E=function(a){if(a.count_!=a.keys_.length){for(var b=0,c=0;b<a.keys_.length;){var d=a.keys_[b];Object.prototype.hasOwnProperty.call(a.map_,d)&&(a.keys_[c++]=d);b++}a.keys_.length=c}if(a.count_!=a.keys_.length){for(var e={},c=b=0;b<a.keys_.length;)d=a.keys_[b],Object.prototype.hasOwnProperty.call(e,d)||(a.keys_[c++]=d,e[d]=1),b++;a.keys_.length=c}};D.prototype.get=function(a,b){return Object.prototype.hasOwnProperty.call(this.map_,a)?this.map_[a]:b};
D.prototype.set=function(a,b){Object.prototype.hasOwnProperty.call(this.map_,a)||(this.count_++,this.keys_.push(a),this.version_++);this.map_[a]=b};D.prototype.addAll=function(a){var b;if(a instanceof D)b=a.getKeys(),a=a.getValues();else{b=[];var c=0,d;for(d in a)b[c++]=d;c=[];d=0;for(var e in a)c[d++]=a[e];a=c}for(e=0;e<b.length;e++)this.set(b[e],a[e])};
D.prototype.__iterator__=function(a){E(this);var b=0,c=this.version_,d=this,e=new C;e.next=function(){if(c!=d.version_)throw Error("The map has changed since the iterator was created");if(b>=d.keys_.length)throw B;var e=d.keys_[b++];return a?e:d.map_[e]};return e};var G=function(a,b,c){this.maxCount_=a||null;this.cache_=!!b;this.evictionCallback_=c;this.map_=new D;this.head_=new F("",void 0);this.head_.next=this.head_.prev=this.head_},I=function(a,b){var c=a.map_.get(b);c&&a.cache_&&(c.remove(),H(a,c));return c};h=G.prototype;h.get=function(a,b){var c=I(this,a);return c?c.value:b};h.set=function(a,b){var c=I(this,a);c?c.value=b:(c=new F(a,b),this.map_.set(a,c),H(this,c))};h.remove=function(a){return(a=this.map_.get(a))?(this.removeNode(a),!0):!1};
h.removeNode=function(a){a.remove();this.map_.remove(a.key)};h.getCount=function(){return this.map_.getCount()};h.getKeys=function(){return this.map(function(a,b){return b})};h.getValues=function(){return this.map(function(a){return a})};h.map=function(a,b){for(var c=[],d=this.head_.next;d!=this.head_;d=d.next)c.push(a.call(b,d.value,d.key,this));return c};
var H=function(a,b){a.cache_?(b.next=a.head_.next,b.prev=a.head_,a.head_.next=b,b.next.prev=b):(b.prev=a.head_.prev,b.next=a.head_,a.head_.prev=b,b.prev.next=b);if(null!=a.maxCount_)for(var c=a.maxCount_;a.getCount()>c;){var d=a.cache_?a.head_.prev:a.head_.next;a.removeNode(d);a.evictionCallback_&&a.evictionCallback_(d.key,d.value)}},F=function(a,b){this.key=a;this.value=b};F.prototype.remove=function(){this.prev.next=this.next;this.next.prev=this.prev;delete this.prev;delete this.next};var K=function(a,b){var c=J.map_.get(a);if(!c||null==b)return null;for(var d=null,e=0;e<c.length&&(d=c[e],d.query!=b&&d.ei!=b);e++);return d};chrome.extension.getVersion=function(){if(!chrome.extension.version_){var a=new XMLHttpRequest;a.open("GET",chrome.extension.getURL("manifest.json"),!1);a.onreadystatechange=function(){if(4==this.readyState){var a=JSON.parse(this.responseText);chrome.extension.version_=a.version}};a.send()}return chrome.extension.version_};var L=function(){this.lastInterval_=null};L.prototype.setImage_=function(a){chrome.pageAction.setIcon({tabId:a,path:"images/page-action-animated_"+this.step_+".png"});this.step_=(this.step_+1)%8};L.prototype.stop=function(){this.lastInterval_&&window.clearInterval(this.lastInterval_)};var S={"search-results":M,"landing-page":N,"found-tidbits":O,"minimized-state":P,"open-link":Q,"get-more-tidbits":R},J=new function(){this.map_=new G(100,!0)},T=new L;
function M(a,b){for(var c=b.results,d=J,e=0;e<c.length;e++){var f=c[e];if(f.href)a:{var l=d,m=l.map_.get(f.href);if(m){for(l=0;l<m.length;l++){var g=m[l];if(g.query==f.query||g.ei==f.ei){g.ei=f.ei;g.fromVisualSnippet=f.fromVisualSnippet;g.vsClickedTidbitIndex=f.vsClickedTidbitIndex;g.query=f.query;g.searchUrl=f.searchUrl;g.tidbits=f.tidbits;g.htmlTidbits=f.htmlTidbits;g.hasEbmTidbits=f.hasEbmTidbits;m.splice(l,1);m.push(g);break a}}m.push(f)}else l.map_.set(f.href,[f])}}}
function N(a,b){var c=a.sender.tab.id,d=K(b.href,b.subkey);if(d&&0<d.tidbits.length)d.debug=d.debug||{},d.debug.version=chrome.extension.getVersion(),d.hasEbmTidbits?U(c,{title:"running",active:!0}):U(c,{active:!0}),chrome.tabs.executeScript(c,{code:"window.qs_result = "+JSON.stringify(d)},function(){V(c,"in-document_content_script.js",function(){d.seen=!0})});else{var e;d?e=chrome.i18n.getMessage("qs_info_non_annotated_result",x(d.query)):y(b.href)&&z(b.href)&&(e=chrome.i18n.getMessage("qs_info_on_search"));
e&&(U(c,{active:!1}),W(c,e))}}function O(a,b){var c=a.sender.tab.id;b.foundTidbits?U(c,{active:!0}):(U(c,{active:!1}),W(c,chrome.i18n.getMessage("qs_info_no_tidbits_found",x(b.result.query))))}function P(a,b){b.result&&(K(b.result.href,b.result.query).minimized=b.minimized)}function Q(a,b){X(b.url)}function X(a){chrome.tabs.getAllInWindow(null,function(b){for(var c=0;c<b.length;c++)if(b[c].url==a){chrome.tabs.update(b[c].id,{selected:!0});return}chrome.tabs.create({url:a,selected:!0})})}
function R(a,b){try{var c=new XMLHttpRequest;c.open("GET",b.url,!0);c.onreadystatechange=function(){4==this.readyState&&a.postMessage({content:this.responseText})};c.send()}catch(d){a.postMessage({content:""})}}
function U(a,b){if("running"==b.title){var c=T;c.stop();c.step_=1;c.lastInterval_=window.setInterval(A(c.setImage_,c,a),300)}else T.stop(),chrome.pageAction.setIcon({tabId:a,path:"images/page-action-"+((b.active?"active":"inactive")+".png")});c=chrome.i18n.getMessage("qs_page_action_"+(b.title||(b.active?"active":"inactive")));chrome.pageAction.setTitle({tabId:a,title:c});chrome.pageAction.show(a)}
function V(a,b,c){var d=chrome.i18n.getMessage("direction");Y(a,"jquery_do_not_compile.js",function(){chrome.tabs.insertCSS(a,{file:"in-document_"+d+"_css.css"},function(){Y(a,b,c)})})}function Y(a,b,c){chrome.tabs.executeScript(a,{file:b},function(){c()})}function W(a,b){V(a,"in-document-message_content_script.js",function(){chrome.tabs.sendRequest(a,{text:b})})}chrome.extension.onConnect.addListener(function(a){a.onMessage.addListener(function(b){if(S[a.name])S[a.name](a,b)})});
chrome.pageAction.onClicked.addListener(function(a){var b=chrome.extension.getURL("about.html");0!=a.url.indexOf("chrome")&&-1==a.url.indexOf("chrome.google.com/extensions")||a.url==b?chrome.tabs.sendRequest(a.id,{toggle:!0}):X(b)});
chrome.webRequest.onBeforeRequest.addListener(function(a){a=a.url;return y(a)&&!z(a)?{redirectUrl:a+"&qscrl=1"}:{}},{urls:"*://www.google.com/search* *://www.google.ae/search* *://www.google.at/search* *://www.google.au/search* *://www.google.be/search* *://www.google.bg/search* *://www.google.ca/search* *://www.google.ch/search* *://www.google.cl/search* *://www.google.cn/search* *://www.google.co.id/search* *://www.google.co.il/search* *://www.google.co.in/search* *://www.google.co.kr/search* *://www.google.co.nz/search* *://www.google.co.jp/search* *://www.google.co.th/search* *://www.google.co.uk/search* *://www.google.co.ve/search* *://www.google.co.za/search* *://www.google.com.ar/search* *://www.google.com.au/search* *://www.google.com.br/search* *://www.google.com.co/search* *://www.google.com.eg/search* *://www.google.com.hk/search* *://www.google.com.mx/search* *://www.google.com.my/search* *://www.google.com.ng/search* *://www.google.com.pe/search* *://www.google.com.ph/search* *://www.google.com.pk/search* *://www.google.com.sa/search* *://www.google.com.sg/search* *://www.google.com.tr/search* *://www.google.com.tw/search* *://www.google.com.ua/search* *://www.google.com.vn/search* *://www.google.cz/search* *://www.google.de/search* *://www.google.dk/search* *://www.google.ee/search* *://www.google.es/search* *://www.google.fi/search* *://www.google.fr/search* *://www.google.gr/search* *://www.google.hr/search* *://www.google.hu/search* *://www.google.ie/search* *://www.google.it/search* *://www.google.lt/search* *://www.google.lv/search* *://www.google.nl/search* *://www.google.no/search* *://www.google.pl/search* *://www.google.pt/search* *://www.google.ro/search* *://www.google.rs/search* *://www.google.ru/search* *://www.google.se/search* *://www.google.si/search* *://www.google.sk/search*".split(" "),types:["main_frame"]},
["blocking"]);
